# Comparison of Boercker and More Ornsten-Zernike 

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from pandas import read_csv

# from hnc.hnc.PIE import Plasma_of_Ions_and_Electrons as PLASMA

from hnc.hnc.hnc_BandM import Integral_Equation_Solver as IET
from hnc.hnc.constants import *
from hnc.hnc.misc import n_from_rs, rs_from_n

from pandas import read_csv

prop_cycle = plt.rcParams['axes.prop_cycle']
colors = prop_cycle.by_key()['color']
                
from IPython.core.display import HTML
HTML("""
<style>
.output_png {
    display: table-cell;
    text-align: center;
    vertical-align: middle;
}

</style>
""")
import matplotlib as mpl
from cycler import cycler
mpl.rcParams['lines.linewidth'] = 2.2
mpl.rcParams['axes.spines.right'] = False
mpl.rcParams['axes.spines.top'] = False
mpl.rcParams['axes.labelsize'] = 20
mpl.rcParams['lines.markersize'] = 8
mpl.rcParams['font.sans-serif'] = ['Arial', 'Tahoma', 'DejaVu Sans', 'Lucida Grande', 'Verdana']
mpl.rcParams['font.size'] = 16
mpl.rcParams['axes.grid'] = True
mpl.rcParams['grid.color'] = '#636363'
mpl.rcParams['grid.alpha'] = 0.12
mpl.rcParams['grid.linewidth'] = 0.7
mpl.rcParams['grid.linestyle'] = '-'
mpl.rcParams['axes.prop_cycle'] = cycler('color',  ['#0AB34F', '#bf009f', '#00abc3', '#8e92c5', '#cc7014', '#e32851'])
mpl.rcParams['legend.fancybox'] = True
mpl.rcParams['legend.framealpha'] = 0.6
mpl.rcParams['legend.fontsize'] = 14
mpl.rcParams['figure.figsize'] = 8, 4.9443
mpl.rcParams['figure.dpi'] = 100


ModuleNotFoundError: No module named 'mendeleev'


In [45]:

a = np.random.rand(2,2,5)
print(a)
a[np.tril_indices(2,-1)]

[[[0.84507957 0.18947278 0.88226001 0.80639171 0.73075478]
  [0.47093326 0.17648407 0.08685481 0.91178196 0.25910815]]

 [[0.52186007 0.94253457 0.78945756 0.95285033 0.29860918]
  [0.55776303 0.53993399 0.41340915 0.80290759 0.76295171]]]


array([[0.52186007, 0.94253457, 0.78945756, 0.95285033, 0.29860918]])

In [56]:
b = np.zeros((2,2,5))
b[np.tril_indices(2,-1)] = a[np.tril_indices(2,-1)]
b = b + np.transpose(b,axes=(1,0,2))
b[np.diag_indices(2)] = a[np.diag_indices(2)]
b

array([[[0.84507957, 0.18947278, 0.88226001, 0.80639171, 0.73075478],
        [0.52186007, 0.94253457, 0.78945756, 0.95285033, 0.29860918]],

       [[0.52186007, 0.94253457, 0.78945756, 0.95285033, 0.29860918],
        [0.55776303, 0.53993399, 0.41340915, 0.80290759, 0.76295171]]])